### ISSUE TITLE
Unexpected reserved word

### ISSUE THREAD

**Issue by nkh** [azu/fz-browse#8]
Hi, I installed with the npm command (got the warning below)
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'react-router@6.8.2',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'react-router-dom@6.8.2',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@remix-run/router@1.3.3',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN deprecated csurf@1.11.0: Please use another csrf package

I ran this command, from your example with changed directory):

fz-browse --run $'find -E ~/downloads -iregex ".*\.(jpg|gif|png|jpeg)$" -print0 | xargs -0 exiftool -q -m -p \'$Directory/$Filename  $DateTimeOriginal  $Comment\' | grep {input} | awk \'{print $1}\'' --preview "echo {target}"
file:///usr/local/lib/node_modules/fz-browse/cli.mjs:66
const server = await createServer({
               ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

**Comment by nkh** [comment]
updating node according to https://www.freecodecamp.org/news/how-to-update-node-and-npm-to-the-latest-version/ got me a bit further, fz-browser start and displays an URL, the URL displays:

Error: Cannot find module 'history'
Require stack:
- /usr/local/lib/node_modules/fz-browse/dist/server/entry-server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at Module._load (node:internal/modules/cjs/loader:934:27)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Module.<anonymous> (/usr/local/lib/node_modules/fz-browse/dist/server/entry-server.js:29:15)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)

**Comment by azu** [comment]
> npm WARN EBADENGINE current: { node: 'v12.22.9', npm: '8.5.1' }

It looks like your node.js is old.
Can you use Node.js 18+?

**Comment by azu** [comment]
> Error: Cannot find module 'history'

https://github.com/azu/fz-browse/blob/d9a22750ee6a1f2bb986bef838258eb62fb640be/package.json `history` is mising.
It

**Comment by nkh** [comment]
Do you have a fix and want me to test?

**Comment by azu** [comment]
fixed in [v1.0.3](https://github.com/azu/fz-browse/releases/tag/v1.0.3)

Can you try it?

**Comment by nkh** [comment]
I re-installed it by running sudo npm install --global fz-browse

It starts OK, serves a page but the only thing it displays is "hit: 0/0"

I'm going to update nodejs, it's 12.xxx right now and get back to you.

**Comment by nkh** [comment]
node -v : v19.7.0
nodejs -v: v12.22.9 (latest package on ubuntu)

then I'm no js dev so I have no idea of what to do next to bring the environment to latest, any hint?
